package aula47.exceptions;

public class Teste {

	public static void main(String[] args) {
		
		try {// tente
			int[] vetor= new int [4];
			System.out.println("Antes da exception");
			
			vetor[4]= 1;
			
			System.out.println("Esse texto não será impresso");

		} catch(ArrayIndexOutOfBoundsException excecption){ // caso ocorra um erro capture a exceção e trate o erro
			System.out.println("Exceção ao acessar um índice do vetor que não existe");
		}
		System.out.println("Esse texto será impresso após a exception");
	}
}
		

